[package]
name = "nsd-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
java-spaghetti = "0.2.0"
jni.workspace = true
log.workspace = true

[workspace]
members = [".", "example_app/example_app_rust_lib/"]

[workspace.dependencies]
log = "0.4.27"
jni = "0.21.1"

nsd-rs.path = "."

[profile.release-with-debug]
inherits = "release"
debug = true
