
include = [
    "com/maticrobots/nsd_rs/*",
    "com/maticrobots/java_rust_obj/*",

    "android/net/nsd/*",
    "android/net/Network",
    "android/content/Context",
    "android/os/Build$VERSION",
    "android/os/Build$VERSION_CODES",
    "android/os/ext/SdkExtensions",

    "java/lang/Object",
    "java/lang/Throwable",
    "java/lang/StackTraceElement",
    "java/lang/String",
    "java/lang/ClassLoader",

    "java/net/InetAddress",

    "java/util/concurrent/Executor",
    "java/util/Collection",
    "java/util/Iterator",
    "java/util/Map",
    "java/util/Map$Entry",
    "java/util/Set",

    "androidx/annotation/NonNull",
    "androidx/annotation/RequiresApi",
]

[[documentation.pattern]]
class_url_pattern = "https://developer.android.com/reference/{CLASS}.html"
method_url_pattern = "https://developer.android.com/reference/{CLASS}.html#{METHOD}({ARGUMENTS})"
constructor_url_pattern = "https://developer.android.com/reference/{CLASS}.html#{CLASS.INNER}({ARGUMENTS})"
field_url_pattern = "https://developer.android.com/reference/{CLASS}.html#{FIELD}"
argument_seperator = ",%20"


[logging]
verbose = true

[input]
files = [
    # TODO Make this respect environment variables
    "/home/abe/Android/Sdk/platforms/android-36-ext19/android.jar",


    "../../target/aarch64-linux-android/debug/build/nsd-rs-ea0f9da5c1da57ae/out/java/com/maticrobots/java_rust_obj/RustArcBoxDynAny.class",
    "../../target/aarch64-linux-android/debug/build/nsd-rs-ea0f9da5c1da57ae/out/java/com/maticrobots/nsd_rs/NSDDiscoveryListener.class",
    "../../target/aarch64-linux-android/debug/build/nsd-rs-ea0f9da5c1da57ae/out/java/com/maticrobots/nsd_rs/NSDServiceResolver.class"
]

[output]
path = "bindings.rs"

[codegen]
method_naming_style = "java"
method_naming_style_collision = "java_short_signature"
keep_rejected_emits = false

[codegen.field_naming_style]
const_finals = true
rustify_names = false
getter_pattern = "{NAME}"
setter_pattern = "set_{NAME}"
