
include = [
    "com/maticrobots/rust_bluedroid/*",
    "com/maticrobots/java_rust_obj/*",

    "android/bluetooth/*",
    "android/content/BroadcastReceiver",
    "android/content/Context",

    "android/os/ParcelUuid",

    "android/util/SparseArray",

    "java/io/IOException",
    "java/io/InputStream",
    "java/io/OutputStream",
    "java/lang/Exception",
    "java/lang/Object",
    "java/lang/Throwable",
    "java/lang/StackTraceElement",
    "java/lang/String",
    "java/lang/ClassLoader",

    "java/util/AbstractCollection",
    "java/util/AbstractList",
    "java/util/Arrays",
    "java/util/ArrayList",
    "java/util/Collection",
    "java/util/List",
    "java/util/Map",
    "java/util/Map$Entry",
    "java/util/Set",
    "java/util/UUID",

    "androidx/annotation/NonNull",
    "androidx/annotation/RequiresApi",
]

[[documentation.pattern]]
class_url_pattern = "https://developer.android.com/reference/{CLASS}.html"
method_url_pattern = "https://developer.android.com/reference/{CLASS}.html#{METHOD}({ARGUMENTS})"
constructor_url_pattern = "https://developer.android.com/reference/{CLASS}.html#{CLASS.INNER}({ARGUMENTS})"
field_url_pattern = "https://developer.android.com/reference/{CLASS}.html#{FIELD}"
argument_seperator = ",%20"


[logging]
verbose = true

[input]
files = [
    # TODO Make this respect environment variables
    "/home/abe/Android/Sdk/platforms/android-35/android.jar",
    # Hack so we can use android studio (as opposed to raw javac) to build the jar files.
    # Technically this may change, but I (Abe) think that is unlikely.
    "../../target/aarch64-linux-android/debug/build/bluedroid-c2354023b21414b6/out/java/com/maticrobots/java_rust_obj/RustArcBoxDynAny.class",
    "../../target/aarch64-linux-android/debug/build/bluedroid-c2354023b21414b6/out/java/com/maticrobots/rust_bluedroid/Adapter.class",
    "../../target/aarch64-linux-android/debug/build/bluedroid-c2354023b21414b6/out/java/com/maticrobots/rust_bluedroid/Scan.class",
    "../../target/aarch64-linux-android/debug/build/bluedroid-c2354023b21414b6/out/java/com/maticrobots/rust_bluedroid/BluetoothDevice.class",
    "../../target/aarch64-linux-android/debug/build/bluedroid-c2354023b21414b6/out/java/com/maticrobots/rust_bluedroid/Optional.class",
    "../../target/aarch64-linux-android/debug/build/bluedroid-c2354023b21414b6/out/java/com/maticrobots/rust_bluedroid/GattCallback.class",
    "../../target/aarch64-linux-android/debug/build/bluedroid-c2354023b21414b6/out/java/com/maticrobots/rust_bluedroid/Service.class",
    "../../target/aarch64-linux-android/debug/build/bluedroid-c2354023b21414b6/out/java/com/maticrobots/rust_bluedroid/ScanInner.class",
    "../../target/aarch64-linux-android/debug/build/bluedroid-c2354023b21414b6/out/java/com/maticrobots/rust_bluedroid/LEScanCallback.class",
    "../../target/aarch64-linux-android/debug/build/bluedroid-c2354023b21414b6/out/java/com/maticrobots/rust_bluedroid/PairingReceiver.class",
]

[output]
path = "bindings.rs"

[codegen]
method_naming_style = "java"
method_naming_style_collision = "java_short_signature"
keep_rejected_emits = false

[codegen.field_naming_style]
const_finals = true
rustify_names = false
getter_pattern = "{NAME}"
setter_pattern = "set_{NAME}"
