[package]
name = "bluedroid"
version = "0.1.0"
edition = "2024"
license = "MIT"

[dependencies]
async-lock = "3.0.0"
java-spaghetti = "0.2.0"
futures-core = "0.3.28"
futures-channel = "0.3.28"
futures-io = "0.3.31"
uuid = "1.17.0"
futures-lite = { version = "1.13.0", default-features = false }
log = "0.4.27"
thiserror = "2.0.12"

java-spaghetti-context.path = "../java-spaghetti-context"
java-spaghetti-result.path = "../java-spaghetti-result"
java-spaghetti-class-loader.path = "../java-spaghetti-class-loader"
java_owned_rust_object.path = "../java_owned_rust_object"
