[workspace]
members = [
    "bluedroid",
    "nsd-rs",
    "nsd-rs/nsd_example_app",
    "bluedroid/bluedroid_example_app",
    "bluedroid/example_app_linux_host",
    "java_owned_rust_object",
    "java-spaghetti-result",
    "java-spaghetti-context",
    "ndk-application-context",
    "java-spaghetti-class-loader",
]
resolver = "3"
