[package]
name = "ndk-application-context"
version = "0.1.0"
edition = "2024"
license = "MIT"

[features]
java-spaghetti = ["dep:java-spaghetti"]

[dependencies]
ndk-context = "0.1.1"
ctor = "0.4.2"
java-spaghetti = {version = "0.2.0", optional = true}

[target.'cfg(target_os = "android")'.dependencies]
android_log-sys = "0.3.2"
