[package]
name = "java_owned_rust_object"
version = "0.1.0"
edition = "2024"

[dependencies]
java-spaghetti = "0.2.0"

java-spaghetti-context.path = "../java-spaghetti-context"
java-spaghetti-result.path = "../java-spaghetti-result"
java-spaghetti-class-loader.path = "../java-spaghetti-class-loader"

[build-dependencies]
android-build = "0.1.3"
